# netlify.toml

[build]
  # 빌드 시 next export 대신 next build만 실행
  command   = "npm run build"
  # Netlify Next.js 플러그인이 .next 폴더를 자동으로 처리합니다
  publish   = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Supabase Storage public bucket으로 가는 프록시 (CDN 캐싱 포함)
[[redirects]]
  from    = "/cdn/illustrations/images/*"
  to      = "https://jtdmtrdqhefekqgfxnpf.supabase.co/storage/v1/object/public/illustrations/images/:splat"
  status  = 200
  force   = true

# 프록시된 이미지에 장기 캐시 헤더 추가
[[headers]]
  for = "/cdn/illustrations/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
