[build]
  command   = "npm run build"
  publish   = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# CORS 헤더 추가
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Supabase Storage public bucket으로 가는 프록시 (CDN 캐싱 포함)
[[redirects]]
  from    = "/cdn/illustrations/images/*"
  to      = "https://jtdmtrdqhefekqgfxnpf.supabase.co/storage/v1/object/public/illustrations/images/:splat"
  status  = 200
  force   = true

# 프록시된 이미지에 장기 캐시 헤더 추가
[[headers]]
  for = "/cdn/illustrations/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API 경로를 Netlify Functions로 리디렉션
[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions-internal/admin/:splat"
  status = 200
  force = true
